### ISSUE TITLE
White blocks when running simulator in Follow Me mode

### ISSUE THREAD

**Issue by sahiljuneja** [udacity/RoboND-QuadRotor-Unity-Simulator#1]
OS - Windows 10 64 bit
Sim - Windows sim, released by Kyle 3 days ago.

There is one person walking in red clothes, so not all people are coming off as white blocks. I am attaching images for reference.

![whiteblock1](https://user-images.githubusercontent.com/12501638/30566337-3d246a60-9ce9-11e7-82e8-32faff0fcdfa.png)

Not sure if the second one is supposed to be intentional or not, but pointing out just in case.
![whiteblock2](https://user-images.githubusercontent.com/12501638/30566377-73c827f0-9ce9-11e7-85da-ee981846d82f.png)

**Comment by danainschool** [comment]
I am seeing the same thing in Mac

**Comment by demi180** [comment]
That was just a cube and a capsule to reference a person's size from when I was making the level. I've turned them off now. Next time someone makes a build they'll be gone.
